In [ ]:
import sys
sys.path.append('..')

In [35]:
from bolt import barray
from bolt.spark import BoltArraySpark
from bolt.local import BoltArrayLocal
import numpy as np

In [61]:
a = np.arange(18).reshape(2,3,3)
print(a)
x = barray(a)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [77]:
# the default split is 1, meaning, over the first axis similar to treating the array like a iterator
# keys are always some combination of axes
# values are nd arrays

for split in range(1,len(a.shape)+1):
    print('-------')
    xs = x.tospark(sc, split)
    print('split = {}, \nkeys:'.format(split))
    print(xs._rdd.keys().collect())
    print('values:')
    print(xs._rdd.values().collect())
    print xs.mask


-------
split = 1, 
keys:
[(0,), (1,)]
values:
[array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]
(1, 0, 0)
-------
split = 2, 
keys:
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]
values:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14]), array([15, 16, 17])]
(1, 1, 0)
-------
split = 3, 
keys:
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 2, 0), (0, 2, 1), (0, 2, 2), (1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 2, 0), (1, 2, 1), (1, 2, 2)]
values:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
(1, 1, 1)
